# -*- coding: utf-8 -*-
"""imags&txt2array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CIsl6uladFIxofF8ILsFsWaLYkab0oZK
"""

import os #optional
from matplotlib.image import imread
import numpy as np


all_images = []
WIDTH=256
HEIGHT=256
path='C:/Users/cober/Desktop/FASE_6/FASE_6_DL/test_resized_256'

all_images = []
for image_path in os.listdir(path):
  img = imread(path+'/'+image_path )
  img = np.array(img).reshape((WIDTH, HEIGHT, 1))
  all_images.append(img)
x_train = np.array(all_images)


#for image_path in os.listdir(path):
#
#    img = imread(path + '/' + image_path)
#    img = np.arange(1 * 1 * 512 * 512).reshape((512, 512, 1))
#    # img = np.array(img).reshape((256, 256, 3)) <- consider this
#    img = img.astype('float32')
#    all_images.append(img)
#print(all_images)